version: "3"
services:
  db:
    build: ./back/src/db/
  backend:
    build: ./back/
    depends_on:
      - db
  nginx:
    build: ./server/
    ports:
      - 80:80
    volumes:
      - ./front/dist/:/usr/share/nginx/html/
    depends_on:
      - db
      - backend
